import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f1f4f6",
        "on-surface": "#181c1e",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#00468a",
        "on-surface-variant": "#45474c",
        "secondary": "#555f71",
        "inverse-surface": "#2d3133",
        "on-tertiary-container": "#5488d6",
        "outline-variant": "#c6c6cc",
        "on-primary-fixed-variant": "#7f2b00",
        "surface-dim": "#d7dadc",
        "surface-tint": "#a63b00",
        "surface-container": "#ebeef0",
        "primary-container": "#3e1100",
        "on-secondary-fixed-variant": "#3d4759",
        "secondary-fixed-dim": "#bdc7dc",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#ffb599",
        "primary-fixed-dim": "#ffb599",
        "surface": "#f7fafc",
        "inverse-on-surface": "#eef1f3",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#d9e3f9",
        "surface-container-high": "#e5e9eb",
        "outline": "#76777c",
        "on-secondary-container": "#596376",
        "primary-fixed": "#ffdbce",
        "on-error": "#ffffff",
        "tertiary-container": "#002045",
        "error-container": "#ffdad6",
        "background": "#f7fafc",
        "surface-bright": "#f7fafc",
        "on-primary-fixed": "#370e00",
        "tertiary-fixed": "#d6e3ff",
        "on-tertiary-fixed": "#001b3c",
        "surface-variant": "#e0e3e5",
        "tertiary": "#00081a",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "secondary-container": "#d6e0f6",
        "on-primary-container": "#eb5700",
        "on-background": "#181c1e",
        "tertiary-fixed-dim": "#a8c8ff",
        "primary": "#160300",
        "on-secondary-fixed": "#121c2c"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Work Sans", "sans-serif"],
        "label": ["Work Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [forms],
}
